import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./index.css";
import dynamic from 'next/dynamic'

const NoSSRKeyContextProvider = dynamic(() => import('@/components/KeyContext/KeyContext'), { ssr: false })

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NoSSRKeyContextProvider>
        <body className={inter.className}>{children}</body>
      </NoSSRKeyContextProvider>
    </html>
  );
}
