services:

  s3-dev:
    image: chrislusf/seaweedfs:latest
    ports:
      - "8333:8333" # S3 API port
      - "9333:9333" # Master UI port (to visually inspect your storage)
    command: "server -s3"
    volumes:
      - ./notes/minio:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID:-root}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY:-password}

  postgres:
    image: postgres:16 # Use a specific, recent Postgres image version
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
