services: 
  mongo:
    image: ghcr.io/danhab99/prisma-mongo-example:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
    ports:
      - 27017:27017
