format:
	go run github.com/steebchen/prisma-client-go format

generate: format
	go run github.com/steebchen/prisma-client-go generate

db: generate
	go run github.com/steebchen/prisma-client-go db push

